Single day screen
aant0ni0/WeatherWonders-app pull request #1
Opened 2024-07-30 11:08 UTC by aant0ni0

2024-08-02 12:01 UTC, KartonM requested changes

2024-08-02 12:01 UTC, KartonM commented on components/Loader.tsx
> +      <ActivityIndicator size="large" color={colors.primary} />
Ten loader wyświetla się niebieski na niebieskim tle, nie widać go.

2024-08-02 12:01 UTC, KartonM commented on services/api.ts
> +const API_KEY = "3f6de936886f0b0bd368ed34bbd07eee";
Wrzucanie kluczy do API na publiczne repo to nie jest dobry pomysł. Możesz go wrzucić w zmienną środowiskową tak, żeby nie był widoczny na repo (każdy kto będzie chciał zbudować i odpalić tą appkę u siebie będzie musiał wtedy dać swój klucz).
https://docs.expo.dev/guides/environment-variables/

Tak produkcyjnie, jeśli korzysta się w appce z takich zewnętrznych API, żeby uniknąć wrzucania klucza w kod aplikacji (skąd można się do niego dobrać) można na przykład zawsze korzystać z API za pośrednictwem własnego backendu (https://reactnative.dev/docs/security#storing-sensitive-info) albo wystawić endpoint, z którego pobiera się klucz (gdzie jeśli zostanie on skompromitowany, można go podmienić)

2024-08-02 12:01 UTC, KartonM commented on screens/SingleDayScreen.tsx
> +  Image,
Nieużywany import

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
W tym pliku są typescriptowe błędy
```
hooks/useWeatherData.ts:66:9 - error TS7034: Variable 'start' implicitly has type 'any' in some locations where its type cannot be determined.

66     let start, end;
           ~~~~~

hooks/useWeatherData.ts:66:16 - error TS7034: Variable 'end' implicitly has type 'any' in some locations where its type cannot be determined.

66     let start, end;
                  ~~~

hooks/useWeatherData.ts:79:28 - error TS7005: Variable 'start' implicitly has an 'any' type.

79         return itemDate >= start && itemDate < end;
                              ~~~~~

hooks/useWeatherData.ts:79:48 - error TS7005: Variable 'end' implicitly has an 'any' type.

79         return itemDate >= start && itemDate < end;
                                                  ~~~


Found 4 errors in the same file, starting at: hooks/useWeatherData.ts:66

```

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +const height = UnistylesRuntime.screen.height;
Tak jak przy tym klonie glovo pisałem, żeby nie używać Dimensions.get('window'), tylko `useWindowDimensions`, tak samo przy Unistyles nie powinniśmy używać tego - te wymiary mogą się zmieniać, w ten sposób sprawdzasz je tylko raz. Zamiast tego definiując style możesz do `createStyleSheet` podać funkcję, która jako parametr dostanie runtime https://reactnativeunistyles.vercel.app/reference/create-stylesheet/#basic-usage-function

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +    height: height / 4.5,
Czemu rozmiary tego obrazka są tak związane z szerokością ekranu? To się sypnie jeśli będziemy chcieli wylayoutować ten widget inaczej niż w tej siatce z 2 kolumnami na całą szerokość ekranu, którą masz teraz

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +    height: "83%",
To powinno być względem samego obrazka z kompasem, a nie kontenera na całość - sypnie się przy zmianie jego wielkości. Generalnie nie ma co przesadzać z przygotowywaniem kodu na wszystkie możliwe zmiany. Ale tutaj to akurat można zrobić niewielkim kosztem. A jeśli komponent sam nie wymusza tego w jaki sposób ma być layoutowany, to wg mnie nie powinien nic o tym zakładać. Poniżej screenshot tego jak to wygląda jak zmieniłem layout tak, żeby mieć 1 kolumnę widgetów zamiast 2. 

![simulator_screenshot_1108D5D6-60BD-4A95-9671-EEE3DE784BD6](https://github.com/user-attachments/assets/2752beec-2b20-4338-95e6-7aa2f9dcc6f8)

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +    left: 6,
To pojawia się nie tylko w tym pliku - ogólnie wszędzie gdzie się da używaj `start`/`end` zamiast `left`/`right`. Tak żeby weszło w krew. No i a nuż okaże się, że kiedyś przyjdzie wymaganie, żeby wspierać w aplikacji jakiś język pisany RTL
https://reactnative.dev/docs/flexbox#layout-direction

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +    <WeatherWidget title="Wind">
Sypie się jeśli tekst nagłówka jest dłuższy. 

![image](https://github.com/user-attachments/assets/8b7d8b90-e2b3-46f1-8476-1c88aef8589c)

Pisząc widoki nie powinniśmy zakładać jakiej długości będzie tekst. Może się okazać, że w przyszłości chcemy go zmienić, albo słowo, które po angielsku ma 4 litery może w innym wspieranym języku mieć 10 liter długości. Oczywiście wszystko w granicach rozsądku - jeśli jakiś komponent jest nagłówkiem nie musimy przygotowywać go na to, żeby był w stanie wyświetlić cały paragraf tekstu

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WindWidget.tsx
> +  avgWindSpeed,
Czemu to są 3 osobne parametry? Jak rozmawialiśmy o wydzieleniu logiki do tego hooka useWeatherData, powiedzieliśmy sobie, że to ma być jedyne miejsce zależne od tego parametru `today`. Cała reszta powinna być taka sama bez względu na to, czy wyświetlamy pogodę dla dzisiejszego dnia, dla jutra czy dla 23. sierpnia 2044. 

Ten komponent wyświetla prędkość wiatru i robi to tak samo bez względu na to o jaki przedział czasu pytamy. Powinien przyjmować jeden parametr - prędkość wiatru

2024-08-02 12:01 UTC, KartonM commented on assets/colors.ts
> +export default colors;
Dobry pomysł ze zdefiniowaniem kolorów w jednym miejscu! Możesz je tylko wrzucić do theme'u i używać ich potem z theme'u jak piszesz style. Dzięki temu będzie się je dało zmienić dynamicznie w trakcie działania appki, jeśli kiedyś pojawi się taka potrzeba. Taki jest w ogóle sens korzystania z tego unistyles.

https://reactnativeunistyles.vercel.app/start/setup/#34-call-unistylesregistry

2024-08-02 12:01 UTC, KartonM commented on App.tsx
> +import { SafeAreaView, StyleSheet, Text, View } from "react-native";
Żaden z tych importów nie jest używany

2024-08-02 12:01 UTC, KartonM commented on components/HourlyForecast.tsx
> +    height: "37%",
Skąd jest te 37%? Zakładam, że to jest sprawdzone na oko tak, żeby nie ucinało tych obrazków. No ale wprowadzamy po cichu zależność od wysokości całości (teraz ustawiona na 200). Zamiast tego, jak już zakładamy, że te ikonki będą miały stałe rozmiary, możemy ustawić po prostu [aspectRatio](https://reactnative.dev/docs/layout-props#aspectratio).

2024-08-02 12:01 UTC, KartonM commented on components/HourlyForecast.tsx
> +    borderRadius: 5,
Pisząc ten styl zakładam, że nie pomyślałeś "5" tylko "taka sama wartość, jaką ustawiłem dla `hourlyWeather`" - niech kod to odzwierciedla

2024-08-02 12:01 UTC, KartonM commented on components/SunriseSunsetChart.tsx
Miejscami słonko się trochę rozjeżdża z tą krzywą, ale super, że w ogóle udało się to zrobić 👏 

![image](https://github.com/user-attachments/assets/91ffe70a-e066-4520-93df-1b282e509942)

Powyżej ustawiłem czas na 5:30. Zostawiam już Tobie to czy chcesz się bawić z poprawieniem tego

2024-08-02 12:01 UTC, KartonM commented on components/widgets/SunriseSunsetWidget.tsx
> +        currentTime={new Date().getTime()}
Fajnie by było jakby ten czas się "odświeżał" co jakiś czas. Tak jak jest teraz, jeśli otworzę appkę rano, zostawię ja w backgroundzie i wejdę do niej z powrotem po południu, słonko wciąż będzie na porannej godzinie

2024-08-02 12:01 UTC, KartonM commented on components/widgets/VisibilityWidget.tsx
> +  avgVisibility,
Tak jak pisałem już przy innym widgecie, tutaj powinien być 1 parametr a w kodzie komponentu nie powinno być logiki zależnej od `today`

2024-08-02 12:01 UTC, KartonM commented on components/widgets/WeatherWidget.tsx
> +    width: "45%",
To jak to layoutowac dobrze by było zostawić rodzicowi - komponentowi, który renderuje te widgety. Najlepiej by było zrobić tak, żeby on przyjmował dodatkowo propsa `style?: StyleProp<ViewStyle>`

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +      }
cool, w sumie nie wiedziałem, że wilgotność i wiatr to są rzeczy, które determinują tą odczuwalną temperaturę w prognozach

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +    mainTempTomorrow,
Tak jak pisałem już wcześniej przy widgetach i mówiłem w biurze - interfejs tego co zwraca ten hook powinien być niezależny od tego dla jakiego dnia jest to prognoza.

2024-08-02 12:01 UTC, KartonM commented on services/api.ts
> +const BASE_URL_WEATHER = "https://api.openweathermap.org/data/2.5/weather";
Czemu 2.5 a nie najnowsza wersja tego API - 3.0?

2024-08-02 12:01 UTC, KartonM commented on screens/SingleDayScreen.tsx
> +  return (
No i super, czytelniejszy się sporo zrobił ten widok. A będzie jeszcze lepiej jak pozbędziemy się tych niepotrzebnych propsów wynikających z tego, że w tych małych komponentach mamy dalej rozsianą logikę wyświetlania innych danych w zależności od dnia

2024-08-02 12:01 UTC, KartonM commented on screens/SingleDayScreen.tsx
> +const insetsTop = UnistylesRuntime.insets.top;
Już gdzieś wyżej pisałem - brać z `runtime` w createStyleSheet

2024-08-02 12:01 UTC, KartonM commented on screens/SingleDayScreen.tsx
> +    paddingTop: "10%",
Nie do końca jestem przekonany co do używania tych % do wielkości marginesów/paddingów. Generalnie ja nigdy tak nie definiuję żadnych wartości. Najczęściej jak dostajemy jakieś designy to spacingi są tam przemyślane tak, żeby pasowały do wielkości innych elementów. No a te nie będą zawsze mogły być ustalane względnie do wielkości ekranu, mogą być na sztywno jak wielkości czcionek (które zresztą u Ciebie są też na sztywno). Do tego zakładam, ze jeśli mam większy ekran, to spodziewam się, że zobaczę na nim więcej rzeczy, a nie, że będę miał większe marginesy.

Skąd w ogóle nawyk, żeby to tak ustawiać? Robił tak ktoś w jakims kursie, który przerabiałeś? Jak to uzasadniał?

2024-08-02 12:01 UTC, KartonM commented on screens/SingleDayScreen.tsx
> +    marginBottom: 25,
Tutaj ten margines jest już na sztywno...

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +    chooseMainWeatherforTomorrow,
Wszystkie dane są tu jako wartości, a to jest jako funkcja. To się nie zmieni bez zmiany całej reszty rzeczy zwracanych stąd, no nie? Do tego jeszcze ta funkcja robi jakieś obliczenia, a potencjalnie moze być wołana wiele razy. Wydaje się, że tą "main weather" też by można było zwracać jako raz wyliczoną wartość. Oczywiście po przerobieniu tego hooka wyliczaną tylko jeśli trzeba ją wyliczać (`!today`)

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +  const changeBackgroundImageDependsOnWeather = () => {
Ta funkcja nie zmienia obrazka, tylko daje obrazek do wyświetlenia. No i tak jak przy "main weather" - to chyba nie musi być zwracane z tego hooka jako funkcja

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +    const mostCommonWeather = sortedWeatherTypes[0]?.[0];
Tutaj to nie zmienia dużo, bo ta liczba nie będzie duża, także trochę się rozdrabniam i pewnie można by się kłócić, że to "premature optimization", ale nic nie zaboli tutaj napisanie tego kodu tak, żeby faktycznie brał max po countach zamiast sortować wszystko. Napisz to `reduce`m.

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +    const weatherCounts: { [key: string]: number } = {};
TS ma utility type na to. Zamiast `{ [key: string]: number }` można użyć `Record<string, number>`

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +    return mostCommonWeather || null;
Generalnie ta funkcja trochę pokazuje jak biedna jest biblioteka standardowa JSa. Na przykład w Kotlinie (pewnie już mówiłem, romantyzowany przeze mnie język) można by to napisać w jednej linijce (rozbitej dla czytelności):
```kotlin
weatherForTommorrow
  .groupingBy { it.weather.first().description }
  .eachCount()
  .maxByOrNull { it.value }
  ?.key
```

2024-08-02 12:01 UTC, KartonM commented on hooks/useWeatherData.ts
> +  const sunrise = weatherData?.sys.sunrise ? weatherData?.sys.sunrise : 0;
`weatherData?.sys.sunrise ?? 0`

2024-08-02 12:01 UTC, KartonM commented on package.json
> +    "react-native-safe-area-context": "4.10.5",
to jest gdzieś używane? dostajemy to już z unistyles, no nie?

2024-08-02 12:01 UTC, KartonM commented on screens/FiveDaysScreen.tsx
> +  }, []);
Całe to jest zduplikowane - samo to fetchowanie też można wydzielić do hooka

2024-08-12 14:31 UTC, aant0ni0 commented on components/Loader.tsx
> +      <ActivityIndicator size="large" color={colors.primary} />
Zmieniłem to na tym nowszym branchu

2024-08-12 14:40 UTC, aant0ni0 commented on components/widgets/VisibilityWidget.tsx
> +  avgVisibility,
Rozwiązałem to na nowszym branchu

2024-08-12 14:40 UTC, aant0ni0 commented on components/widgets/VisibilityWidget.tsx
> +  avgVisibility,
Rozwiązałem to na nowszym branchu

2024-08-12 14:44 UTC, aant0ni0 commented on components/widgets/WindWidget.tsx
> +  avgWindSpeed,
Równiez rozwiązane w nowszym branchu

2024-08-12 15:03 UTC, aant0ni0 commented on package.json
> +    "react-native-safe-area-context": "4.10.5",
to prawda, nie jest uzywane

2024-08-12 15:03 UTC, aant0ni0 commented on screens/FiveDaysScreen.tsx
> +  }, []);
Wszystko jest zrobione w tym nowszym branchu

2024-08-13 10:08 UTC, aant0ni0 commented on components/widgets/SunriseSunsetWidget.tsx
> +        currentTime={new Date().getTime()}
dodałem odświezanie co 15 min

2024-08-13 10:30 UTC, aant0ni0 commented on components/widgets/WeatherWidget.tsx
> +    width: "45%",
Dodałem propsa ale tez zalozenie tych widgetow jest takie ze sa one spojne wygladowo wiec colosc stylowania mam przeniesc do rodzica, czy tylko drobne szczegoly?

2024-08-13 11:00 UTC, aant0ni0 commented on components/widgets/WindWidget.tsx
> +    left: 6,
Sprawdzilem i start/end nie dziala przy uzywaniu unistyles

2024-08-13 11:30 UTC, aant0ni0 commented on hooks/useWeatherData.ts
> +    chooseMainWeatherforTomorrow,
To wszystko bedzie zmienione na nowszym branchu

2024-08-13 12:02 UTC, aant0ni0 commented on services/api.ts
> +const BASE_URL_WEATHER = "https://api.openweathermap.org/data/2.5/weather";
W dokumentacji do api ktorego uzywam podana jest wersja 2.5, jesli chodzi ci o One Call 3.0 api to ono jest platne

2024-08-13 12:04 UTC, aant0ni0 commented on services/api.ts
> +const API_KEY = "3f6de936886f0b0bd368ed34bbd07eee";
Oki

2024-08-13 13:01 UTC, aant0ni0 commented on components/widgets/WindWidget.tsx
> +    <WeatherWidget title="Wind">
ale w tym wypadku musialbym zmniejszyc kompas a wtedy bedzie on slabo widoczny

2024-08-13 13:28 UTC, aant0ni0 commented on components/widgets/WindWidget.tsx
> +    height: "83%",
Poprawilem calosc, teraz przy zmianie wielkosci widgetu wszystko jest w porzadu

2024-08-13 13:50 UTC, aant0ni0 commented on assets/colors.ts
> +export default colors;
Wrzuciłem do theme'u

2024-08-13 13:52 UTC, aant0ni0 commented on screens/SingleDayScreen.tsx
> +    paddingTop: "10%",
Poprawilem, chyba mi to jeszcze z technikum zostalo ale masz racje ze lepiej na sztywno

2024-08-14 12:04 UTC, merged